# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 18:03
from __future__ import unicode_literals

import buggy.enums
from django.conf import settings
import django.contrib.postgres.fields.citext
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import enumfields.fields
from django.contrib.postgres.operations import CITextExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        CITextExtension(),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('bug', 'order'),
            },
        ),
        migrations.CreateModel(
            name='AddAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to='attachments/')),
            ],
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('state', enumfields.fields.EnumField(enum=buggy.enums.State, max_length=25)),
                ('priority', enumfields.fields.EnumIntegerField(enum=buggy.enums.Priority)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', django.contrib.postgres.fields.citext.CICharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('action', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='buggy.Action')),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SetAssignment',
            fields=[
                ('action', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='buggy.Action')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SetPriority',
            fields=[
                ('action', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='buggy.Action')),
                ('priority', enumfields.fields.EnumIntegerField(enum=buggy.enums.Priority)),
            ],
        ),
        migrations.CreateModel(
            name='SetProject',
            fields=[
                ('action', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='buggy.Action')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='buggy.Project')),
            ],
        ),
        migrations.CreateModel(
            name='SetState',
            fields=[
                ('action', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='buggy.Action')),
                ('state', enumfields.fields.EnumField(enum=buggy.enums.State, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='SetTitle',
            fields=[
                ('action', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='buggy.Action')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='bug',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='buggy.Project'),
        ),
        migrations.AddField(
            model_name='addattachment',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buggy.Action'),
        ),
        migrations.AddField(
            model_name='action',
            name='bug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='buggy.Bug'),
        ),
        migrations.AddField(
            model_name='action',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='action',
            unique_together=set([('bug', 'order')]),
        ),
    ]
