# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 22:39
from __future__ import unicode_literals

import buggy.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('buggy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='addattachment',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='buggy.Action'),
        ),
        migrations.AlterField(
            model_name='addattachment',
            name='file',
            field=models.FileField(max_length=255, upload_to=buggy.models.attachment_upload_to),
        ),
    ]
