# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buggy', '0002_auto_20170418_1639'),
        ('buggy', '0002_add_preset_filter'),
    ]

    operations = [
    ]
