# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buggy', '0003_merge_20170419_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='fulltext',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.RunSQL(
            """
            CREATE INDEX buggy_bug_fulltext_index
              ON buggy_bug
              USING gin (to_tsvector('english', COALESCE(fulltext, '')));
            """,
            """
            DROP INDEX buggy_bug_fulltext_index;
            """
        ),
    ]
