# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buggy', '0004_bug_fulltext'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE INDEX bug_state_assigned_to_index ON buggy_bug (assigned_to_id) WHERE (state != 'closed');
            """,
            """
            DROP INDEX bug_state_assigned_to_index;
            """
        )
    ]
